name: fds
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.3.2
  firebase_core: ^2.5.0
  google_sign_in: ^5.4.4
  firebase_auth: ^4.2.6
  flutter_slidable: ^1.2.0
  shared_preferences: ^2.0.8

  flutter_riverpod: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
